name: Build Documentation

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Build Docs
        run: |
          cd docs
          mkdocs build --clean
