name: Security & Dependabot

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 3 * * 1" # Tous les lundis à 03:00

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: ["javascript", "python"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependabot:
    name: Dependabot Auto Merge
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Auto-merge Dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
